<a href="https://colab.research.google.com/github/Frh-2506/data-science-toolkit/blob/main/Tutorial_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np
list=[2,6,4,9]
numpy_array=np.array(list).reshape(2,2)
print("Numpy array 2x2:\n",numpy_array)

Numpy array 2x2:
 [[2 6]
 [4 9]]


In [46]:
import numpy as np
random_array=np.random.rand(3,4)
print("Random array 3X4:\n",random_array)

Random array 3X4:
 [[0.57089663 0.59887905 0.07475786 0.39476445]
 [0.34944131 0.24008733 0.38592615 0.31992228]
 [0.97307699 0.76863816 0.97047417 0.64601846]]


In [35]:
import numpy as np
zero_array=np.zeros((3,3))
one_array=np.ones((4,3))
print("Zeros array:\n",zero_array)
print("Ones array:\n",one_array)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [47]:
import numpy as np
random_array=np.random.rand(6,3)
print("Random array:\n",random_array)
transpose_array=np.transpose(random_array)
print("Transpose for random array:\n",transpose_array)

Random array:
 [[0.50147352 0.76131477 0.44317449]
 [0.53973244 0.3160979  0.9465593 ]
 [0.52530235 0.6550594  0.59553143]
 [0.77073663 0.94164367 0.13785738]
 [0.8583822  0.56905021 0.40220028]
 [0.51256306 0.27902769 0.5977931 ]]
Transpose for random array:
 [[0.50147352 0.53973244 0.52530235 0.77073663 0.8583822  0.51256306]
 [0.76131477 0.3160979  0.6550594  0.94164367 0.56905021 0.27902769]
 [0.44317449 0.9465593  0.59553143 0.13785738 0.40220028 0.5977931 ]]


In [43]:
import numpy as np
random_array1=np.random.rand(2,4)
random_array2=np.random.rand(4,3)
print("Array number 1:\n",random_array1)
print("Array number 2:\n",random_array2)
product=np.dot(random_array1,random_array2)
print("Dot product:\n",product)


Array number 1:
 [[0.81096928 0.0063863  0.71450307 0.452597  ]
 [0.92192696 0.31568848 0.54487475 0.56477901]]
Array number 2:
 [[0.57550114 0.77739318 0.29617231]
 [0.79907203 0.63620291 0.58068249]
 [0.69651446 0.88933382 0.45180544]
 [0.94697108 0.49808599 0.26032891]]
Dot product:
 [[1.39807485 1.49536894 0.68453551]
 [1.69717038 1.68342572 0.84956969]]
